// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPRU4LJhNUsgSpJkmIUn4EQ6fQcUU7hU',
    appId: '1:1040528876799:web:887359868bb8e3f97918ca',
    messagingSenderId: '1040528876799',
    projectId: 'baraka-bliss-staycations',
    authDomain: 'baraka-bliss-staycations.firebaseapp.com',
    storageBucket: 'baraka-bliss-staycations.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFUBLL4n-g2jzS5Laf3WVSvRRv6ix71Y',
    appId: '1:1040528876799:android:3a7312abe6ee47147918ca',
    messagingSenderId: '1040528876799',
    projectId: 'baraka-bliss-staycations',
    storageBucket: 'baraka-bliss-staycations.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkGBdpuGQt8T0Kx0qp57hntXWAQ-d-ZI',
    appId: '1:1040528876799:ios:17e766d4ae7c61937918ca',
    messagingSenderId: '1040528876799',
    projectId: 'baraka-bliss-staycations',
    storageBucket: 'baraka-bliss-staycations.firebasestorage.app',
    iosBundleId: 'com.example.barakaBlissStaycations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkGBdpuGQt8T0Kx0qp57hntXWAQ-d-ZI',
    appId: '1:1040528876799:ios:17e766d4ae7c61937918ca',
    messagingSenderId: '1040528876799',
    projectId: 'baraka-bliss-staycations',
    storageBucket: 'baraka-bliss-staycations.firebasestorage.app',
    iosBundleId: 'com.example.barakaBlissStaycations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEPRU4LJhNUsgSpJkmIUn4EQ6fQcUU7hU',
    appId: '1:1040528876799:web:44cb42b5c912a5b37918ca',
    messagingSenderId: '1040528876799',
    projectId: 'baraka-bliss-staycations',
    authDomain: 'baraka-bliss-staycations.firebaseapp.com',
    storageBucket: 'baraka-bliss-staycations.firebasestorage.app',
  );

}